name: Build Hashcheck on Kali

on:
  push:
    branches: [ build ]
  pull_request:
    branches: [ build ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kalilinux/kali-rolling

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y \
          build-essential \
          cmake \
          make \
          gcc \
          hashcat \
          rapidjson-dev \
          seclists

    - name: Compile Hashcheck
      run: |
        cd src
        make

    - name: Verify binary
      run: |
        ls -l src/hashcheck-rc || { echo "Binary not found"; exit 1; }

    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: hashcheck-binary
        path: src/hashcheck-rc


