name: Build Hashcheck on Kali

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kalilinux/kali-rolling

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y \
          build-essential \
          cmake \
          make \
          gcc \
          hashcat \
          seclists

    - name: Compile Hashcheck
      run: |
        cd src
        make

    - name: Verify binary
      run: |
        ls -l src/hashcheck || { echo "❌ Binary not found"; exit 1; }

    - name: Test with Seclists
      run: |
        TEST_WORDLIST="/usr/share/seclists/Passwords/Common-Credentials/10k-most-common.txt"
        if [ -f "$TEST_WORDLIST" ]; then
          echo "✅ Found seclists wordlist: $TEST_WORDLIST"
          # Example run (replace with your actual syntax)
          ./src/hashcheck --wordlist "$TEST_WORDLIST" --hash "5f4dcc3b5aa765d61d8327deb882cf99"
        else
          echo "❌ Seclists not found"; exit 1
        fi
