name: Release Hashcheck Deb Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: kalilinux/kali-rolling

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install build & packaging dependencies
      run: |
        apt-get update
        apt-get install -y \
          g++ \
          make \
          pkg-config \
          libssl-dev \
          dpkg-dev \
          fakeroot \
          rapidjson-dev \
          hashcat \
          seclists

    - name: Build Hashcheck
      run: |
        make
        mkdir -p package/usr/bin
        cp bin/hashcheck package/usr/bin/hashcheck

    - name: Create DEBIAN control file
      run: |
        mkdir -p package/DEBIAN

        cat <<EOF > package/DEBIAN/control
        Package: hashcheck
        Version: ${GITHUB_REF_NAME#v}
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: Hashcheck Maintainers <richard@richardcallaby.com>
        Depends: hashcat, rapidjson-dev, seclists
        Description: Hashcheck - A hash detection and cracking automation tool
         Hashcheck determines hash types and automatically supplies the right 
         arguments to hashcat to crack them.
        EOF

    - name: Build .deb package
      run: |
        dpkg-deb --build --root-owner-group package hashcheck_${GITHUB_REF_NAME}_amd64.deb

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: "hashcheck ${{ github.ref_name }}"
        draft: false
        prerelease: false
        files: hashcheck_${{ github.ref_name }}_amd64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
