name: Release Hashcheck Packages

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-deb:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: kalilinux/kali-rolling

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build & packaging dependencies
        run: |
          apt-get update
          apt-get install -y \
            g++ \
            make \
            pkg-config \
            libssl-dev \
            dpkg-dev \
            fakeroot \
            librapidjson-dev \
            hashcat \
            seclists

      - name: Build Hashcheck
        run: |
          make
          mkdir -p package/usr/bin
          cp bin/hashcheck package/usr/bin/hashcheck

      - name: Create DEBIAN control file
        run: |
          mkdir -p package/DEBIAN
          cat <<EOF > package/DEBIAN/control
          Package: hashcheck-rc
          Version: ${GITHUB_REF_NAME#v}
          Section: utils
          Priority: optional
          Architecture: amd64
          Maintainer: Hashcheck-rc Maintainers <richard@richardcallaby.com>
          Depends: hashcat, librapidjson-dev, seclists
          Description: Hashcheck-rc - A hash detection and cracking automation tool 
           Hashcheck determines hash types and automatically supplies the right 
           arguments to hashcat to crack them.
          EOF

      - name: Build .deb package
        run: |
          dpkg-deb --build --root-owner-group package hashcheck-rc_${GITHUB_REF_NAME#v}_amd64.deb

      - name: Upload deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: hashcheck-rc_${GITHUB_REF_NAME#v}_amd64.deb
          retention-days: 1

  build-rpm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: fedora:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build & packaging dependencies
        run: |
          dnf check-update -y
          dnf install -y \
            gcc-c++ \
            make \
            pkgconfig \
            openssl-devel \
            rpm-build \
            rapidjson-devel \
            hashcat \
            seclists

      - name: Build Hashcheck
        run: make

      - name: Prepare RPM build environment
        run: |
          mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
          cp bin/hashcheck ~/rpmbuild/SOURCES/hashcheck.tar.gz

      - name: Create RPM spec file
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          cat > ~/rpmbuild/SPECS/hashcheck-rc.spec << EOF
          Name: hashcheck-rc
          Version: ${VERSION}
          Release: 1%{?dist}
          Summary: Hashcheck-rc - A hash detection and cracking automation tool
          License: GPL
          BuildArch: x86_64
          Source: %{name}-%{version}.tar.gz
          Requires: hashcat, rapidjson-devel, seclists

          %description
          Hashcheck determines hash types and automatically supplies the right
          arguments to hashcat to crack them.

          %prep
          %setup -q -n hashcheck-rc-%{version}

          %build
          make

          %install
          rm -rf %{buildroot}
          mkdir -p %{buildroot}/usr/bin
          cp hashcheck %{buildroot}/usr/bin/hashcheck
          chmod 755 %{buildroot}/usr/bin/hashcheck

          %files
          %defattr(-,root,root,-)
          /usr/bin/hashcheck

          %changelog
          * $(date "+%a %b %d %Y") Richard Callaby <richard@richardcallaby.com> - ${VERSION}-1
          - Initial RPM package
          EOF

      - name: Build RPM package
        run: |
          rpmbuild -ba ~/rpmbuild/SPECS/hashcheck-rc.spec

      - name: Upload rpm artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpm-package
          path: ~/rpmbuild/RPMS/x86_64/*.rpm
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: [build-deb, build-rpm]
    permissions:
      contents: write
    steps:
      - name: Download deb artifact
        uses: actions/download-artifact@v4
        with:
          name: deb-package
          path: artifacts/deb-package

      - name: Download rpm artifact
        uses: actions/download-artifact@v4
        with:
          name: rpm-package
          path: artifacts/rpm-package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "hashcheck-rc ${{ github.ref_name }}"
          draft: false
          prerelease: false
          files: |
            artifacts/deb-package/*.deb
            artifacts/rpm-package/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}