name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Ruby for fpm
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Install fpm
        run: gem install --no-document fpm

      - name: Build .deb package
        env:
          VERSION: ${{ github.ref_name }}   # e.g. v1.2.3
        run: |
          VERSION="${VERSION#v}"
          mkdir -p packages/usr/local/bin
          cp bin/hashcheck-binary packages/usr/local/bin/hashcheck-binary

          # Build DEB
          fpm -s dir -t deb -n hashcheck -v "$VERSION" -a amd64 \
              --description "HashCheck - detects hash types & runs hashcat" \
              --license "MIT" \
              --url "https://github.com/${{ github.repository }}" \
              -d "hashcat" \
              -d "seclists" \
              -C packages usr \
              -p hashcheck_${VERSION}_amd64.deb

      - name: Publish GitHub Release with package
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            hashcheck_*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
